The dataset contains 36733 instances of 11 sensor measures aggregated over one hour (by means of average or sum) from a gas turbine. 
The Dataset includes gas turbine parameters (such as Turbine Inlet Temperature and Compressor Discharge pressure) in addition to the ambient variables.



Problem statement: predicting turbine energy yield (TEY) using ambient variables as features.



Attribute Information:

The explanations of sensor measurements and their brief statistics are given below.

Variable (Abbr.) Unit Min Max Mean
Ambient temperature (AT) C –6.23 37.10 17.71
Ambient pressure (AP) mbar 985.85 1036.56 1013.07
Ambient humidity (AH) (%) 24.08 100.20 77.87
Air filter difference pressure (AFDP) mbar 2.09 7.61 3.93
Gas turbine exhaust pressure (GTEP) mbar 17.70 40.72 25.56
Turbine inlet temperature (TIT) C 1000.85 1100.89 1081.43
Turbine after temperature (TAT) C 511.04 550.61 546.16
Compressor discharge pressure (CDP) mbar 9.85 15.16 12.06
Turbine energy yield (TEY) MWH 100.02 179.50 133.51
Carbon monoxide (CO) mg/m3 0.00 44.10 2.37
Nitrogen oxides (NOx) mg/m3 25.90 119.91 65.29

In [1]:
import numpy as np
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler,MinMaxScaler

In [3]:
df=pd.read_csv('gas_turbines.csv')
df

AT      AP      AH    AFDP    GTEP     TIT     TAT     TEY     CDP  \
0      6.8594  1007.9  96.799  3.5000  19.663  1059.2  550.00  114.70  10.605   
1      6.7850  1008.4  97.118  3.4998  19.728  1059.3  550.00  114.72  10.598   
2      6.8977  1008.8  95.939  3.4824  19.779  1059.4  549.87  114.71  10.601   
3      7.0569  1009.2  95.249  3.4805  19.792  1059.6  549.99  114.72  10.606   
4      7.3978  1009.7  95.150  3.4976  19.765  1059.7  549.98  114.72  10.612   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
15034  9.0301  1005.6  98.460  3.5421  19.164  1049.7  546.21  111.61  10.400   
15035  7.8879  1005.9  99.093  3.5059  19.414  1046.3  543.22  111.78  10.433   
15036  7.2647  1006.3  99.496  3.4770  19.530  1037.7  537.32  110.19  10.483   
15037  7.0060  1006.8  99.008  3.4486  19.377  1043.2  541.24  110.74  10.533   
15038  6.9279  1007.2  97.533  3.4275  19.306  1049.9  545.85  111.58  10.583   

           CO     NOX  
0      3.1547  82.722  
1      3.2363  82.776  
2      3.2012  82.468  
3      3.1923  82.670  
4      3.2484  82.311  
...       ...     ...  
15034  4.5186  79.559  
15035  4.8470  79.917  
15036  7.9632  90.912  
15037  6.2494  93.227  
15038  4.9816  92.498  

[15039 rows x 11 columns]

In [4]:
df.shape

(15039, 11)

In [5]:
df.info

<bound method DataFrame.info of            AT      AP      AH    AFDP    GTEP     TIT     TAT     TEY     CDP  \
0      6.8594  1007.9  96.799  3.5000  19.663  1059.2  550.00  114.70  10.605   
1      6.7850  1008.4  97.118  3.4998  19.728  1059.3  550.00  114.72  10.598   
2      6.8977  1008.8  95.939  3.4824  19.779  1059.4  549.87  114.71  10.601   
3      7.0569  1009.2  95.249  3.4805  19.792  1059.6  549.99  114.72  10.606   
4      7.3978  1009.7  95.150  3.4976  19.765  1059.7  549.98  114.72  10.612   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
15034  9.0301  1005.6  98.460  3.5421  19.164  1049.7  546.21  111.61  10.400   
15035  7.8879  1005.9  99.093  3.5059  19.414  1046.3  543.22  111.78  10.433   
15036  7.2647  1006.3  99.496  3.4770  19.530  1037.7  537.32  110.19  10.483   
15037  7.0060  1006.8  99.008  3.4486  19.377  1043.2  541.24  110.74  10.533   
15038  6.9279  1007.2  97.533  3.4275  19.306  1049.9  545.85  111.58  10.583

In [6]:
df.describe()

AT           AP            AH          AFDP          GTEP  \
count  15039.000000  15039.00000  15039.000000  15039.000000  15039.000000   
mean      17.764381   1013.19924     79.124174      4.200294     25.419061   
std        7.574323      6.41076     13.793439      0.760197      4.173916   
min        0.522300    985.85000     30.344000      2.087400     17.878000   
25%       11.408000   1008.90000     69.750000      3.723900     23.294000   
50%       18.186000   1012.80000     82.266000      4.186200     25.082000   
75%       23.862500   1016.90000     90.043500      4.550900     27.184000   
max       34.929000   1034.20000    100.200000      7.610600     37.402000   

                TIT           TAT           TEY           CDP            CO  \
count  15039.000000  15039.000000  15039.000000  15039.000000  15039.000000   
mean    1083.798770    545.396183    134.188464     12.102353      1.972499   
std       16.527806      7.866803     15.829717      1.103196      2.222206   
min     1000.800000    512.450000    100.170000      9.904400      0.000388   
25%     1079.600000    542.170000    127.985000     11.622000      0.858055   
50%     1088.700000    549.890000    133.780000     12.025000      1.390200   
75%     1096.000000    550.060000    140.895000     12.578000      2.160400   
max     1100.800000    550.610000    174.610000     15.081000     44.103000   

                NOX  
count  15039.000000  
mean      68.190934  
std       10.470586  
min       27.765000  
25%       61.303500  
50%       66.601000  
75%       73.935500  
max      119.890000

In [7]:
df.isnull().sum()

AT      0
AP      0
AH      0
AFDP    0
GTEP    0
TIT     0
TAT     0
TEY     0
CDP     0
CO      0
NOX     0
dtype: int64

In [11]:
x = df.loc[:,['AT', 'AP', 'AH', 'AFDP', 'GTEP', 'TIT', 'TAT', 'CDP', 'CO','NOX']]
y= df.loc[:,['TEY']]
standard = StandardScaler()
x = standard.fit_transform(x)
y = standard.fit_transform(y) 

In [14]:
x.shape

(15039, 10)

In [15]:
y.shape

(15039, 1)

In [25]:
from keras.models import Sequential
from keras.layers import Dense,InputLayer,Dropout
from sklearn.model_selection import KFold
from keras.wrappers.scikit_learn import KerasRegressor
from tensorflow.keras.optimizers import Adam
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import cross_val_score



In [69]:
def create_model():
    model=Sequential()
    model.add(Dense(10,input_dim=10,kernel_initializer='random_uniform',activation='tanh'))
    model.add(Dense(1,activation='sigmoid'))
   
    
    model.compile(loss='mean_squared_error',optimizer='adam',metrics=['accuracy'])
    return model

In [71]:
import warnings
warnings.filterwarnings('ignore')
estimator=KerasRegressor(build_fn=create_model,epochs=50,batch_size=100,verbose=0)
kfold=KFold(n_splits=10)
results=cross_val_score(estimator,x,y,cv=kfold)

KeyboardInterrupt: 

In [72]:
results.mean()

-0.5589800745248794

In [73]:
estimator.fit(x,y)
pred=estimator.predict(x)
pred

array([0.999964  , 0.999964  , 0.99996406, ..., 0.9999623 , 0.9999626 ,
       0.9999631 ], dtype=float32)

In [74]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)
estimator.fit(x_train, y_train)
prediction = estimator.predict(x_test)
prediction

array([0.9998657 , 0.9998782 , 0.9998732 , ..., 0.9998635 , 0.99985504,
       0.99987984], dtype=float32)

In [75]:
X = df.drop(columns = ['TEY'], axis = 1) 
y = df.iloc[:,7]
from sklearn.preprocessing import scale
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.1, random_state = 42)
x_train_scaled = scale(x_train)
x_test_scaled = scale(x_test)
x_test_scaled

array([[ 0.82623246, -0.43954308, -0.25924569, ...,  0.10039242,
        -0.3796304 , -0.69217007],
       [ 0.35282087,  0.23279782,  0.80230139, ..., -1.18541222,
         0.39149515, -1.09475442],
       [ 0.32839008, -0.07135639,  0.25312287, ...,  0.01665304,
        -0.00296896, -0.31891741],
       ...,
       [-0.74071701,  0.37687087,  0.43427425, ...,  1.77157829,
        -1.00127821, -0.4818816 ],
       [-0.49965786, -0.39151873,  0.64680105, ..., -0.26517949,
        -0.48137538,  0.12808615],
       [ 0.13151427,  0.32884652,  0.98830762, ..., -1.40331469,
         0.13152215, -0.64456466]])

In [87]:
predictions_df = pd.DataFrame()
predictions_df['Actual'] = y
predictions_df['Pred'] = pred
predictions_df['% Error'] = abs(predictions_df['Actual'] - predictions_df['Pred'])/predictions_df['Actual']*100
predictions_df

Actual      Pred    % Error
0      114.70  0.999964  99.128192
1      114.72  0.999964  99.128344
2      114.71  0.999964  99.128268
3      114.72  0.999964  99.128344
4      114.72  0.999964  99.128344
...       ...       ...        ...
15034  111.61  0.999963  99.104056
15035  111.78  0.999963  99.105419
15036  110.19  0.999962  99.092511
15037  110.74  0.999963  99.097018
15038  111.58  0.999963  99.103815

[15039 rows x 3 columns]

In [89]:
import tensorflow as tf
input_size = 10
output_size = 1
hidden_layer_size = 50

model = tf.keras.Sequential([
                                
                               tf.keras.layers.Dense(hidden_layer_size, input_dim = input_size, activation = 'relu'),
                               tf.keras.layers.Dense(hidden_layer_size, activation = 'relu'),
                               tf.keras.layers.Dense(hidden_layer_size, activation = 'relu'),
                               tf.keras.layers.Dense(hidden_layer_size, activation = 'relu'),     
                               tf.keras.layers.Dense(output_size)
                             ])

In [90]:
optimizer = tf.keras.optimizers.SGD(learning_rate = 0.03)
model.compile(optimizer = 'adam', loss = 'mean_squared_error', metrics = ['MeanSquaredError'])
num_epochs = 100
early_stopping = tf.keras.callbacks.EarlyStopping(patience = 2)
model.fit(x_train_scaled, y_train, callbacks = early_stopping, validation_split = 0.1, epochs = num_epochs, verbose = 2)

Epoch 1/100
381/381 - 2s - loss: 2836.8528 - mean_squared_error: 2836.8528 - val_loss: 170.5534 - val_mean_squared_error: 170.5534 - 2s/epoch - 6ms/step
Epoch 2/100
381/381 - 1s - loss: 94.9041 - mean_squared_error: 94.9041 - val_loss: 71.8521 - val_mean_squared_error: 71.8521 - 743ms/epoch - 2ms/step
Epoch 3/100
381/381 - 1s - loss: 43.5697 - mean_squared_error: 43.5697 - val_loss: 36.1963 - val_mean_squared_error: 36.1963 - 731ms/epoch - 2ms/step
Epoch 4/100
381/381 - 1s - loss: 23.0744 - mean_squared_error: 23.0744 - val_loss: 20.6720 - val_mean_squared_error: 20.6720 - 733ms/epoch - 2ms/step
Epoch 5/100
381/381 - 1s - loss: 12.5295 - mean_squared_error: 12.5295 - val_loss: 10.5433 - val_mean_squared_error: 10.5433 - 789ms/epoch - 2ms/step
Epoch 6/100
381/381 - 1s - loss: 7.0232 - mean_squared_error: 7.0232 - val_loss: 6.1149 - val_mean_squared_error: 6.1149 - 736ms/epoch - 2ms/step
Epoch 7/100
381/381 - 1s - loss: 4.0800 - mean_squared_error: 4.0800 - val_loss: 3.5474 - val_mean_sq

In [91]:
test_loss, mean_squared_error = model.evaluate(x_test_scaled, y_test)


47/47 [==============================] - 0s 2ms/step - loss: 0.7295 - mean_squared_error: 0.7295


In [92]:
predictions = model.predict_on_batch(x_test_scaled)
plt.scatter(y_test, predictions)

In [93]:
predictions_df = pd.DataFrame()
predictions_df['Actual'] = y_test
predictions_df['Predicted'] = predictions
predictions_df['% Error'] = abs(predictions_df['Actual'] - predictions_df['Predicted'])/predictions_df['Actual']*100
predictions_df.reset_index(drop = True)

Actual   Predicted   % Error
0     134.46  135.207779  0.556135
1     111.88  112.538261  0.588364
2     133.72  134.430496  0.531331
3     133.79  134.705612  0.684365
4     110.77  111.218674  0.405050
...      ...         ...       ...
1499  132.85  133.101379  0.189220
1500  125.07  122.672050  1.917286
1501  160.95  160.820587  0.080406
1502  133.12  133.191849  0.053973
1503  111.79  112.157578  0.328811

[1504 rows x 3 columns]